/**
 * Copyright 2015 Alan Drees
 *
 * Purpose:
 *   Javascript implementation for the mediadoc test application
 *
 * Dependencies:
 *   jQuery
 *   jQueryUI
 *   AD ajax lib
 */

var MDT = MDT || {};

if(typeof MDT !== 'undefined')
{
    MDT.colours = {};

    MDT.target = "votes-output";
}

/**\fn MDT.populate_color_list
 *
 * Populates the javascript internal structure
 *
 * @param data (object) data object generated by
 *
 * @returns None
 */

MDT.populate_color_list = function()
{
    AD.AjaxAPI.ajax_api_call('/ajax.php',
			     'get_colour_list',
			     '',
			     function(data)
			     {
				 var colour = "";

				 for(var i = 0; i < data.json.colours.length; i++)
				 {
				     colour = data.json.colours[i];
				     MDT.colours[colour] = new MDT.Colour(colour, MDT.colour_renderer);
				 }

				 MDT.colours['Total'] = new MDT.Total(MDT.colours, MDT.colour_renderer);

				 MDT.build_color_table();
			     },
			     undefined,
			     function(data)
			     {
				 console.log(data);
			     }
			    );
}
